apiVersion: v1
kind: Service
metadata:
  name: task-backend
  labels:
    app: task-backend
spec:
  selector:
    app: task-backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
